apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-local.fullname" . }}-secret
  labels:
    {{- include "postgresql-local.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }} 