apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-local.fullname" . }}-secret
  labels:
    {{- include "mysql-local.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.auth.rootPassword | b64enc | quote }} 