apiVersion: v1
kind: Secret
metadata:
  name: final-test-credentials
  namespace: dbaas-final-test
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=
  password: dGVzdDEyMw==
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: final-test-cluster
  namespace: dbaas-final-test
spec:
  instances: 3
  imageName: postgres:15-alpine
  postgresql:
    parameters:
      max_connections: '200'
      shared_buffers: 128MB
      effective_cache_size: 512MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: '0.9'
      wal_buffers: 16MB
  bootstrap:
    initdb:
      database: testdb
      owner: admin
      secret:
        name: final-test-credentials
  storage:
    size: 1Gi
    storageClass: standard
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
