apiVersion: v1
kind: Secret
metadata:
  name: admin.scale-test-cluster.credentials.postgresql.acid.zalan.do
  namespace: dbaas-scale-test
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: dGVzdDEyMw==  # test123
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: scale-test-cluster
  namespace: dbaas-scale-test
spec:
  teamId: "dbaas"
  volume:
    size: 1Gi
  numberOfInstances: 3  # 처음에는 3개로 시작
  users:
    admin:
      - superuser
      - createdb
  databases:
    testdb: admin
  postgresql:
    version: "15"
    parameters:
      max_connections: "200"
      shared_buffers: "128MB"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi 