apiVersion: v1
kind: Secret
metadata:
  name: test-ha-restored-credentials
  namespace: dbaas-test-ha-restored
type: kubernetes.io/basic-auth
data:
  username: ZGJ1c2Vy
  password: cG9zdGdyZXMxMjM=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-ha-restored-cluster
  namespace: dbaas-test-ha-restored
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  postgresql:
    parameters:
      max_connections: '200'
      shared_buffers: 128MB
      effective_cache_size: 512MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: '0.9'
      wal_buffers: 16MB
  bootstrap:
    initdb:
      database: testdb
      owner: dbuser
      secret:
        name: test-ha-restored-credentials
  storage:
    size: 1Gi
    storageClass: standard
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
