apiVersion: v1
kind: Secret
metadata:
  name: admin.zalando-test-cluster.credentials.postgresql.acid.zalan.do
  namespace: dbaas-zalando-test
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: dGVzdDEyMw==  # test123
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: zalando-test-cluster
  namespace: dbaas-zalando-test
spec:
  teamId: "dbaas"
  volume:
    size: 1Gi
  numberOfInstances: 3
  users:
    admin:
      - superuser
      - createdb
  databases:
    testdb: admin
  postgresql:
    version: "15"
    parameters:
      max_connections: "200"
      shared_buffers: "128MB"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi 